import { NextResponse } from "next/server";
import { getSkillBySlugData } from "@/lib/skills-data";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { slug, variables } = body;

    const skill = getSkillBySlugData(slug);

    if (!skill) {
      return NextResponse.json({ error: "Skill not found" }, { status: 404 });
    }

    // Validate required variables
    const missingRequired = skill.variables.required.filter(
      (v) => !variables[v.name]
    );

    if (missingRequired.length > 0) {
      return NextResponse.json(
        {
          error: "Missing required variables",
          missing: missingRequired.map((v) => v.name),
        },
        { status: 400 }
      );
    }

    // Generate mock output (in production, this would call Claude API)
    const output = generateSkillOutput(skill, variables);

    return NextResponse.json({
      success: true,
      skill: skill.name,
      output,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to generate output" },
      { status: 500 }
    );
  }
}

function generateSkillOutput(
  skill: NonNullable<ReturnType<typeof getSkillBySlugData>>,
  variables: Record<string, string>
): string {
  const skillName = skill.name.split(".")[1].replace(/_/g, " ");
  const varsDisplay = Object.entries(variables)
    .filter(([, value]) => value)
    .map(([key, value]) => `  - **${key.replace(/_/g, " ")}**: ${value}`)
    .join("\n");

  return `# ${skillName.charAt(0).toUpperCase() + skillName.slice(1)}

## Overview
This output was generated using the **${skill.name}** skill from the ${skill.phase} phase.

## Input Configuration
${varsDisplay || "No variables provided"}

## Generated Deliverables

${skill.outputs
  .map(
    (output, i) => `### ${i + 1}. ${output}

This section provides detailed content for "${output}". In production, Claude AI
would generate comprehensive, contextual content based on your specific inputs
and organizational context.

#### Key Insights
- Insight derived from your input parameters
- Actionable recommendation based on best practices
- Strategic consideration for your use case

#### Next Steps
1. Review and customize the generated content
2. Share with relevant stakeholders
3. Iterate based on feedback
`
  )
  .join("\n")}

---
*Generated by AI SkillsPro*
*Skill: ${skill.name}*
*Phase: ${skill.phase}*
*Generated: ${new Date().toISOString()}*
`;
}
